name: Catalyst
version: "0.2.0"
main: org.anvilpowered.catalyst.bungee.plugin.CatalystBungee
api-version: 1.13
authors: [STG_Allen]
description: A cross-platform Essentials plugin
website: https://ci.anvilpowered.org
softdepend: [Anvil, LuckPerms]
